/**
 * Balancer
 * Simple iperf load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: vinogradov.alek@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.ServerAddr

import io.swagger.client.infrastructure.*

class ClientApi(basePath: kotlin.String = "http://localhost:8080/Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0") : ApiClient(basePath) {

    /**
     * obtain iperf server ip list to connect to
     * Return servers ip list
     * @return kotlin.Array<ServerAddr>
     */
    @Suppress("UNCHECKED_CAST")
    fun clientObtainIp(): kotlin.Array<ServerAddr> {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/addr"
        )
        val response = request<kotlin.Array<ServerAddr>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ServerAddr>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
