/**
 * Balancer
 * Simple iperf load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: vinogradov.alek@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param ip 
 * @param port port of Service server
 * @param portIperf port of iperf server
 * @param time 
 */
data class ServerAddr (

    val ip: kotlin.String? = null,
    /* port of Service server */
    val port: kotlin.Int,
    /* port of iperf server */
    val portIperf: kotlin.Int,
    val time: java.time.LocalDateTime? = null
) {
}